package Constant

const (
	WEB_SITE = "ZeroVideo"
	EMAIL = "zerochl0912@gmail.com"
	AUTHOR = "zero"
	AUTHOR_WEBSITE = "http://xinghai.party/blog"

	VIDEO_PREFIX_HOME_CAROUSEL_KEY = "HOME_VIDEO_CAROUSEL"
	VIDEO_PREFIX_HOME_RECOMMEND_KEY = "HOME_VIDEO_RECOMMEND"
	VIDEO_PREFIX_HOME_TV_KEY = "HOME_VIDEO_TV"
	VIDEO_PREFIX_HOME_TV_HOT_KEY = "HOME_VIDEO_TV_HOT"
	VIDEO_PREFIX_HOME_MOVIE_KEY = "HOME_VIDEO_MOVIE"
	VIDEO_PREFIX_HOME_CARTOON_KEY = "HOME_VIDEO_CARTOON"
	VIDEO_PREFIX_HOME_LIVE_KEY = "HOME_LIVE"
	VIDEOS_KEY = "HOME_VIDEOS" //混合解析方式

	CRAWLER_TYPE_IQY = "IQY";
	CRAWLER_TYPE_LETV = "LETV";
	CRAWLER_TYPE_PANDA = "PANDA";
	CRAWLER_TYPE_YOUKU = "YouKu";
	CRAWLER_TYPE_QQ = "QQ";
)
